name: Evaluation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - open3d
  - matplotlib
  - tqdm
  - ffmpeg
  - pip
  - pip:
      - opencv-python
      - git+https://github.com/Vlhermitte/lamar-benchmark.git#egg=lamar[scantools]