name: Evaluation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - open3d
  - matplotlib
  - tqdm
  - ffmpeg
  - pip
    - opencv-python
    -e git+https://github.com/microsoft/lamar-benchmark.git#egg=lamar[scantools]