name: Evaluation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - open3d
  - matplotlib
  - tqdm
  - ffmpeg
  - plotly
  - pandas
  - pillow
  - pip
  - pip:
      - pycolmap==3.10
      - opencv-python